{{ if .Values.app.secrets_from_env }}
apiVersion: v1
kind: Secret
metadata:
  name: dummy-acyl-secrets
data:
  aws_access_key_id: "YXNkZg=="
  aws_secret_access_key: "YXNkZg=="
  github_hook_secret: "YXNkZg=="
  github_token: "YXNkZg=="
  api_keys: "YXNkZg=="
  slack_token: "YXNkZg=="
  tls_cert: "YXNkZg=="
  tls_key: "YXNkZg=="
  db_uri: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczpyb290QHBvc3RncmVzcWwtcG9zdGdyZXNxbDo1NDMyL2FjeWw/c3NsbW9kZT1kaXNhYmxl"
{{ end }}
