{{- if .Values.ingress.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: acyl-traefik
  annotations:
    "kubernetes.io/ingress.class": "{{ .Values.ingress.traefik.ingress_class }}"
spec:
  entryPoints:
    - {{ .Values.ingress.traefik.entry_point }}
  routes:
  {{- if .Values.is_dqa }}
  - match: Host(`{{ .Values.env_name }}-{{ .Values.ingress.traefik.host }}`)
  {{- else }}
  - match: Host(`{{ .Values.ingress.traefik.host }}`)
  {{- end }}
    kind: Rule
    services:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.internalPort }}
  tls:
  {{- if .Values.ingress.traefik.tls_secret_name }}
    secretName: {{ .Values.ingress.traefik.tls_secret_name }}
  {{- else }}
    certResolver: default
  {{- end }}
{{- end }}
